messenger4j:
  appSecret: 2fe8db629957ff05f670a53f709a327f
  verifyToken : kjvkfJ22KDgd8Jds
  pageAccessToken: EAAE0z7DYHZAIBAOCgIXALxFEVZAHMcUDDfI31ZBmspXnLUqn2knCs3PZCdXfohnaMQBQgeMBWQbBppCL8aMIEv9qfFFXgi3TKK7QNK5AxtHI6kNFM6ebZCAGcwD8H3CoctZBQ5uB9bftSAnti2kfa1byVzH6eD3AfPqAWToO1wKQZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO
